// web_apps/welcome-app/src/App.svelte
<script>
  import { onMount } from 'svelte';
  
  let logoVisible = false;
  let titleVisible = false;
  let darknessVisible = true;
  let beepSound;
  
  onMount(async () => {
    // Create audio object for sound effects
    beepSound = new Audio('/sounds/beep.wav');
    beepSound.volume = 0.3;
    
    // Start the darkness reveal animation
    setTimeout(() => {
      darknessVisible = false;
      playSound();
    }, 300);
    
    // Trigger logo animation after darkness reveal
    setTimeout(() => {
      logoVisible = true;
      playSound();
    }, 2600);
    
    // Trigger title animation
    setTimeout(() => {
      titleVisible = true;
      playSound();
    }, 3300);
  });
  
  function playSound() {
    if (beepSound) {
      // Reset sound to beginning and play
      beepSound.currentTime = 0;
      beepSound.play().catch(e => console.log("Sound play prevented by browser policy:", e));
    }
  }
</script>

<div class="app-container">
  <!-- Darkness overlay that reveals the content -->
  <div class="darkness-overlay" class:revealed={!darknessVisible}></div>
  
  <div class="welcome-screen">
    <div class="logo-container">
      <img 
        src="/images/saraylo-logo.png" 
        alt="SARAYLO Logo" 
        class="logo"
        class:visible={logoVisible}
      />
    </div>
    
    <div class="title-container">
      <h1 class="app-title" class:visible={titleVisible}>SARAYLO</h1>
      <p class="app-subtitle" class:visible={titleVisible}>Ваш персональный квантовый беговой тренер</p>
    </div>
  </div>
</div>

<style>
  :global(body) {
    margin: 0;
    padding: 0;
    background: linear-gradient(135deg, #000033, #33001a);
    font-family: 'Arial', sans-serif;
    height: 100vh;
    overflow: hidden;
  }
  
  .app-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    width: 100%;
  }
  
  /* Darkness overlay that covers the entire screen initially */
  .darkness-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: #000000;
    z-index: 1000;
    transition: opacity 2.3s cubic-bezier(0.22, 0.61, 0.36, 1);
    opacity: 1;
  }
  
  .darkness-overlay.revealed {
    opacity: 0;
    pointer-events: none;
  }
  
  .welcome-screen {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    width: 100%;
    max-width: 551px;
    margin: 0 auto;
    padding: 20px;
    box-sizing: border-box;
  }
  
  .logo-container {
    margin-bottom: 15px;
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
  }
  
  .logo {
    width: 250px;
    height: 250px;
    opacity: 0;
    transform: scale(0.5);
    transition: all 1s cubic-bezier(0.175, 0.885, 0.32, 1.275);
  }
  
  .logo.visible {
    opacity: 1;
    transform: scale(1);
  }
  
  .title-container {
    text-align: center;
    margin-top: -10px;
  }
  
  .app-title {
    color: #00BFFF;
    font-size: 24px;
    font-weight: bold;
    margin: 0 0 10px 0;
    opacity: 0;
    transform: translateY(20px);
    transition: all 0.8s ease-out 0.3s;
    text-shadow: 0 0 10px rgba(0, 191, 255, 0.5);
  }
  
  .app-title.visible {
    opacity: 1;
    transform: translateY(0);
  }
  
  .app-subtitle {
    color: white;
    font-size: 16px;
    margin: 0;
    opacity: 0;
    transform: translateY(20px);
    transition: all 0.8s ease-out 0.5s;
  }
  
  .app-subtitle.visible {
    opacity: 1;
    transform: translateY(0);
  }
  
  /* Glassmorphism effect for future use */
  .glass-panel {
    background: rgba(255, 255, 255, 0.1);
    backdrop-filter: blur(10px);
    border: 1px solid rgba(255, 255, 255, 0.2);
    border-radius: 15px;
    box-shadow: 0 8px 32px 0 rgba(0, 191, 255, 0.1);
  }
</style>

// ai_running_backend/gui/src/App.vue
<template>
  <div id="app">
    <router-view />
  </div>
</template>

<script>
export default {
  name: 'App'
}
</script>

<style>
/* Global styles */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: 'Arial', sans-serif;
  background: linear-gradient(135deg, #000033, #33001a);
  color: #fff;
  min-height: 100vh;
}

/* Glassmorphism effect */
.glass-effect {
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
  border-radius: 15px;
  box-shadow: 0 8px 32px 0 rgba(0, 191, 255, 0.1);
}

/* Button styles */
.btn {
  padding: 12px 24px;
  border: none;
  border-radius: 8px;
  font-weight: bold;
  cursor: pointer;
  transition: all 0.3s ease;
  text-align: center;
  display: inline-block;
}

.btn-primary {
  background: linear-gradient(45deg, #00BFFF, #FF1493);
  color: white;
}

.btn-secondary {
  background: rgba(255, 255, 255, 0.2);
  color: white;
}

.btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
}

/* Container styles */
.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
}

/* Card styles */
.card {
  background: rgba(255, 255, 255, 0.05);
  border-radius: 10px;
  padding: 20px;
  margin-bottom: 20px;
}

/* Typography */
h1, h2, h3 {
  margin-bottom: 15px;
}

h1 {
  font-size: 2rem;
  text-align: center;
}

h2 {
  font-size: 1.5rem;
}

p {
  line-height: 1.6;
  margin-bottom: 10px;
}

/* Responsive Design */
@media (max-width: 768px) {
  .container {
    padding: 15px;
  }
  
  h1 {
    font-size: 1.8rem;
  }
  
  h2 {
    font-size: 1.3rem;
  }
  
  .btn {
    padding: 10px 20px;
    font-size: 0.9rem;
  }
  
  .card {
    padding: 15px;
  }
}

@media (max-width: 480px) {
  .container {
    padding: 10px;
  }
  
  h1 {
    font-size: 1.5rem;
  }
  
  h2 {
    font-size: 1.2rem;
  }
  
  .btn {
    padding: 8px 16px;
    font-size: 0.8rem;
    width: 100%;
    margin-bottom: 10px;
  }
  
  /* Stack elements on small screens */
  .plan-header {
    flex-direction: column;
    gap: 15px;
  }
  
  .plan-summary {
    grid-template-columns: repeat(2, 1fr);
  }
  
  .checkbox-group {
    grid-template-columns: 1fr;
  }
  
  .form-actions {
    flex-direction: column;
  }
}

/* Large screens */
@media (min-width: 1200px) {
  .container {
    max-width: 1400px;
  }
  
  h1 {
    font-size: 2.5rem;
  }
  
  h2 {
    font-size: 1.8rem;
  }
}
</style>
